FROM python:3.11-slim
WORKDIR /app
COPY ["Sistema de Chamados TI/backend/requirements.txt", "requirements.txt"]
RUN pip install --no-cache-dir -r requirements.txt
COPY ["Sistema de Chamados TI/backend/", "./"]
EXPOSE 8000
CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
